src/flasker/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from flasker.views import Index

urlpatterns = [
    path('',Index.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('publications/', include('publications.urls', namespace='publications'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICDEV_DIR)

src/publications/urls.py
from django.urls import path
from publications import views

app_name = 'publications'

urlpatterns = [
    path('', views.PublicationsListView.as_view(), name='publications'),
    path('create/', views.PublicationCreateView.as_view(), name='publication_create'),
    path('<int:pk>/', views.PublicationDetailView.as_view(), name='publication_detail'),
    path('<int:pk>/edit/', views.PublicationEditView.as_view(), name='publication_update'),
    path('<int:pk>/delete/', views.PublicationDeleteView.as_view(), name='publication_delete'),
    path('<int:pubId>/comment-create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('<int:Id>/comment-delete/', views.CommentDeleteView.as_view(), name='comment_delete')
]

src/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('reset-password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('restablish-password/', views.RestablishPasswordView.as_view(), name='restablish_password'),

    # Authentication
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Isaias Alvarez">
    <meta name="description" content="A blog with made with django">

    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    
    <!-- Awesomefont icons -->
    <script src="https://kit.fontawesome.com/bd43079ab2.js" crossorigin="anonymous"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
    <title>Flasker</title>
</head>
<body class="bg-dark-subtle">
    {% include 'navbar.html' %}

    <div class="container">
        {% block body %}{% endblock %}
    </div>

    {% include 'footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
</body>
</html>

src/templates/footer.html
<div class="footer bg-dark text-white d-flex justify-content-center align-items-center">
    <div class="">
        <p class="text-bold"><i class="fa-regular fa-copyright"></i> Flasker 2023</p>
    </div>
</div>

src/templates/index.html
{% extends 'base.html' %}

{% block body %}

    <h1>WELCOME TO FLASKER!</h1>
    <hr>

    {% if user.is_authenticated %}
    
        <div class="bg-light rounded p-2 shadow">
            <h4>
                {{ user.username }}
            </h4>
        </div>
    
    {% else %}
        <div class="bg-light rounded p-2 shadow">
            <h4><a href="{% url 'users:login' %}">Log In!</a></h4>
            <p>
                Don't have an account? Register <a href="{% url 'users:register' %}">Here</a>
            </p>
        </div>
    {% endif %}



{% endblock %}

src/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary shadow mb-5">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Flasker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                <a class="nav-link" href="{% url 'publications:publications' %}">Publications</a>


            </div>
            
            <div class="navbar-nav ms-auto">
                {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'users:login' %}">Log In</a>
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                
                {% else %}
                    <a class="nav-link m-auto" href="{% url 'users:profile' %}">Profile</a>
                    <a class="nav-link" href="{% url 'users:logout' %}">Log Out</a>
                {% endif %}


            </div>
        </div>
    </div>
</nav>