src/flasker/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from flasker.views import Index

urlpatterns = [
    path('',Index.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('publications/', include('publications.urls', namespace='publications'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICDEV_DIR)

src/publications/urls.py
from django.urls import path
from publications import views

app_name = 'publications'

urlpatterns = [
    path('', views.PublicationsListView.as_view(), name='publications'),
    path('create/', views.PublicationCreateView.as_view(), name='publication_create'),
    path('<int:pk>/', views.PublicationDetailView.as_view(), name='publication_detail'),
    path('<int:pk>/edit/', views.PublicationEditView.as_view(), name='publication_update'),
    path('<int:pk>/delete/', views.PublicationDeleteView.as_view(), name='publication_delete'),
    path('<int:pubId>/comment-create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('<int:Id>/comment-delete/', views.CommentDeleteView.as_view(), name='comment_delete')
]

src/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('reset-password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('restablish-password/', views.RestablishPasswordView.as_view(), name='restablish_password'),

    # Authentication
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

src/publications/models.py
from django.db import models
from datetime import date

# Create your models here.
class Publication(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE, related_name='publications')
    title = models.CharField('Title', max_length=255)
    text = models.TextField('Text', blank=True, null=True)
    image = models.ImageField('Image', blank=True, null=True)
    pub_date = models.DateField('Pub Date', default=date.today)
    isVisible = models.BooleanField('Is Visible', default=True)

    class Meta:
        verbose_name = 'Publication'
        verbose_name_plural = 'Publications'


    def __str__(self) -> str:
        return f'{self.title} {self.author.username}'


    def __repr__(self) -> str:
        return f'<Publication> {self.__str__()}'
    
    

class Comment(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='pub_comments')
    pub_date = models.DateField('Pub Date')
    publication = models.ForeignKey('publications.Publication', on_delete=models.CASCADE, related_name='comments')
    text = models.TextField('Text')

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    
    def __str__(self) -> str:
        return f'{self.publication.title} {self.author.username}'
    

    def __repr__(self) -> str:
        return f'<Comment> {self.__str__()}'

src/publications/forms.py
from django import forms

from publications.models import Publication, Comment

class PublicationForm(forms.ModelForm):
    class Meta:
        model = Publication
        fields = ('title', 'text')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

src/publications/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone

from publications.models import Publication, Comment
from publications.forms import PublicationForm, CommentForm



# Create your views here.
class PublicationsListView(generic.ListView):
    model = Publication
    template_name = 'publications.html'
    context_object_name = 'publications'


    def get_queryset(self):
        publications = self.model.objects.order_by('-pub_date').all()
        return publications


class PublicationCreateView(generic.CreateView):
    model = Publication
    form_class = PublicationForm
    template_name = 'publication_create.html'


    def get_success_url(self, pk) -> str:
        return reverse('publications:publication_detail', kwargs={'pk': pk})


    def form_valid(self, form: PublicationForm):
        
        publication:Publication = form.save(commit=False)
        publication.author = self.request.user
        publication.pub_date = timezone.now()
        publication.save()

        return redirect(self.get_success_url(publication.pk))


class PublicationEditView(generic.UpdateView):
    model = Publication
    form_class = PublicationForm
    template_name = 'publication_edit.html'

    def get_success_url(self) -> str:
        return reverse('publications:publication_detail', kwargs={'pk': self.kwargs['pk']})
    

class PublicationDeleteView(generic.DeleteView):
    model = Publication
    template_name = 'publication_confirm_delete.html'
    success_url = reverse_lazy('publications:publications')


class PublicationDetailView(generic.DetailView):
    model = Publication
    template_name = 'publication_view.html'


class CommentCreateView(generic.RedirectView):

    def post(self, request, *args, **kwargs):
        
        text = request.POST.get('text')
        pubId = self.kwargs['pubId']
        pub = get_object_or_404(Publication, pk=pubId);

        comment = Comment()
        comment.text = text
        comment.publication = pub
        comment.author = request.user
        comment.pub_date = timezone.now()
        comment.save()

        return redirect(reverse('publications:publication_detail', kwargs={'pk': self.kwargs['pubId']}))


class CommentDeleteView(generic.RedirectView):
    http_method_names = ['post',]
    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=self.kwargs['Id'])
        comment.delete()        

        return redirect(reverse('publications:publication_detail', kwargs={'pk': comment.publication.pk}))

src/publications/templates/publication_confirm_delete.html
{% extends 'base.html' %}

{% block body %}

    <div class="bg-dark text-white rounded p-3" style="margin-left: 20%; margin-right: 20%;">
        <h4 class="text-center">Do you wish to delete the publication {{ publication.title }}?</h4>
        <form method="post">
            {% csrf_token %}
            <div class="d-flex justify-content-center">
                <a href="{% url 'publications:publication_detail' pk=publication.pk %}" class="btn btn-warning">Cancel</a>
                <input type="submit" value="Delete" class="btn btn-outline-danger ms-1">
            </div>
        </form>
    </div>

{% endblock %}

src/publications/templates/publication_create.html
{% extends 'base.html' %}

{% block body %}

    <h1>Create Publication</h1>
    <hr>
    <form method="post" class="bg-dark p-3 rounded text-white">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <label for="" class="form-label">{{ form.title.label }}</label>
        <div>
            {{ form.title.errors }}
            {{ form.title }}
        </div>
        
        <label for="" class="form-label">{{ form.text.label }}</label>
        <div>
            {{ form.text.errors }}
            {{ form.text }}
        </div>
        <div class="d-flex mt-2">
            <a href="{% url 'publications:publications' %}" class="ms-auto btn btn-outline-warning">Cancel</a>
            <input type="submit" value="Publish" class="btn btn-light ms-1">
        </div>    
        </form>

{% endblock %}

src/publications/templates/publication_edit.html
{% extends 'base.html' %}

{% block body %}

    <h1>Edit Publication</h1>
    <hr>
    <form method="post" class="bg-dark p-3 rounded text-white">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <label for="" class="form-label">{{ form.title.label }}</label>
        <div>
            {{ form.title.errors }}
            {{ form.title }}
        </div>

        <label for="">{{ form.text.label }}</label>
        <div>
            {{ form.text.errors }}
            {{ form.text }}
        </div>
        <div class="d-flex mt-2">
            <a href="{% url 'publications:publication_detail' pk=publication.pk %}" class="ms-auto btn btn-outline-warning">Cancel</a>
            <input type="submit" value="Save" class="btn btn-light ms-1">
        </div>

    </form>
        
{% endblock %}

src/publications/templates/publication_view.html
{% extends 'base.html' %}

{% block body %}
    <h1>{{ publication.title }}</h1>
    <a href="{% url 'publications:publication_update' pk=publication.pk %}" style="text-decoration: none;" >Edit <i class="fa-solid fa-pencil"></i></a>
    <a href="{% url 'publications:publication_delete' pk=publication.pk %}" style="text-decoration: none;">Delete <i class="fa-regular fa-trash-can"></i></a>
    <hr>
    <div class="bg-light p-3 rounded mt-4 mb-4 shadow">
        <p>{{ publication.text }}</p>
        {{ publication.author }} {{ publication.pub_date }}
    </div>

    <div class="mb-3">
        <h4>Comments</h4>
        <button id="add-commentbtn" class="btn btn-sm btn-primary">Add Comment</button>
        <hr>
        <div id="pub-comments">

            {% for comment in publication.comments.all %}
            <div class="bg-light p-2 d-flex rounded align-items-center">
                <div>
                    <p>{{ comment.text }}</p>
                    <small>{{ comment.author }} {{ comment.pub_date }}</small>
                </div>
                <form action="{% url 'publications:comment_delete' Id=comment.pk %}" method="post" class="ms-auto">
                    {% csrf_token %}
                    <input type="submit" value="X" class="btn btn-outline-danger">
                </form>
                <!-- <a href="{% url 'publications:comment_delete' Id=comment.pk %}">X</a> -->
                
            </div>
            {% empty %}
            <strong>No Comments Found!</strong>
            
            {% endfor %}
        </div>

        <form method="post"
            action="{% url 'publications:comment_create' pubId=publication.pk %}"
            id="comment-form"
            style="display: none; margin-left: 20%; margin-right: 20%;"
            class="bg-dark p-3 rounded">
            {% csrf_token %}
            <label for="" class="form-label text-white">Comment</label>
            <div class="mb-2">
                <textarea name="text" id="text" cols="30" rows="10" class="form-control"></textarea>
                <!-- <input type="text" id="text" name="text" class="form-control"> -->
            </div>
            <div class="d-flex">
                <button type="button" id="cancel-form-btn" class="ms-auto btn btn-outline-warning">Cancel</button>
                <button type="submit" class="ms-1 btn btn-light">Add Comment</button>
            </div>

        </form>
    </div>

    <script>
        let commentForm = document.getElementById('comment-form');
        let commentsDiv = document.getElementById('pub-comments');
        let addCommentBtn = document.getElementById('add-commentbtn');
        let cancelFormBtn = document.getElementById('cancel-form-btn');

        addCommentBtn.addEventListener('click',event=>{
            commentForm.style.display = 'block';
            commentsDiv.style.display = 'none';
        });

        cancelFormBtn.addEventListener('click', event=>{
            commentForm.style.display = 'none';
            commentsDiv.style.display = 'block';
        });

    </script>
{% endblock %}

src/publications/templates/publications.html
{% extends 'base.html' %}

{% block body %}

    <h1>Publications</h1>
    <a href="{% url 'publications:publication_create' %}" style="text-decoration: none;">Add Publication <i class="fa-sharp fa-solid fa-plus"></i></a>
    <hr>

    {% for pub in publications %}
        <div class="bg-light p-2 rounded d-flex align-items-center mb-3">
            <div>
                <a href="{% url 'publications:publication_detail' pk=pub.pk %}">{{ pub.title }}</a> <br>
                <small> <strong>By:</strong> {{ pub.author.username }}</small>
            </div>
                <small class="ms-auto">{{ pub.pub_date }}</small>
        </div>

    {% empty %}
        <h4>No Publications Yet!</h4>
    {% endfor %}


{% endblock %}