src/flasker/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from flasker.views import Index

urlpatterns = [
    path('',Index.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('publications/', include('publications.urls', namespace='publications'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICDEV_DIR)

src/publications/urls.py
from django.urls import path
from publications import views

app_name = 'publications'

urlpatterns = [
    path('', views.PublicationsListView.as_view(), name='publications'),
    path('create/', views.PublicationCreateView.as_view(), name='publication_create'),
    path('<int:pk>/', views.PublicationDetailView.as_view(), name='publication_detail'),
    path('<int:pk>/edit/', views.PublicationEditView.as_view(), name='publication_update'),
    path('<int:pk>/delete/', views.PublicationDeleteView.as_view(), name='publication_delete'),
    path('<int:pubId>/comment-create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('<int:Id>/comment-delete/', views.CommentDeleteView.as_view(), name='comment_delete')
]

src/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('reset-password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('restablish-password/', views.RestablishPasswordView.as_view(), name='restablish_password'),

    # Authentication
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

src/users/models.py
from django.db import models

from pathlib import Path


def upload_handler(instance, filename) -> str:
    """
    Upload Handler

    Creates the path and name for the UserExtension profile_pic
    The result is store in the media directory specified on the
    settings.py file.
    """
    ext = Path(filename).suffix
    res = Path() / 'profilepics' / f'{instance.user.username}.{ext}'
    return str(res)
    


class UserExtension(models.Model):
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE, related_name='extension')
    birthdate = models.DateField('Birth Date')
    profile_pic = models.ImageField('Profile Pic', upload_to=upload_handler, null=True, blank=True)


    def __str__(self) -> str:
        return f'{self.user.username}'


    def __repr__(self) -> str:
        return f'<User Extension> {self.__str__()}'


    def delete(self, *args, **kwargs):
        img = Path(self.profile_pic.path)

        if img.exists():
            img.unlink()
        
        super().delete()

src/users/forms.py
from django import forms
from django.contrib.auth.models import User

from datetime import date
from calendar import monthrange
from users.models import UserExtension

MONTHS = [
    (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'),
    (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'),
    (9, 'Septiembre'),  (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')
]


class UserRegistrationForm(forms.Form):
    username = forms.CharField(max_length=255, min_length=8, widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=255,  widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=255,  widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))

    day = forms.IntegerField(
                            max_value=31,
                            min_value=1,
                            initial=date.today().day,
                            widget=forms.Select(
                                choices=[
                                    (day,day) for day in range(1, 31)
                                ],
                                attrs={'class': 'form-select'}
                            )
                        )
    month = forms.IntegerField(
                            max_value=12,
                            min_value=1,
                            initial=MONTHS[date.today().month - 1],
                            widget=forms.Select(choices=MONTHS, attrs={'class': 'form-select'})
                        )
    year = forms.IntegerField(
                            min_value=1900,
                            max_value=date.today().year,
                            initial=date.today().year,
                            widget=forms.Select(
                                    choices=[
                                        (year, year) for year in range(1900, date.today().year + 1)
                                    ],
                                    attrs={'class': 'form-select'}
                                )
                            )
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    verify_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


    def clean_verify_password(self):
        password = self.cleaned_data['password']
        v_password = self.cleaned_data['verify_password']

        if password != v_password:
            raise forms.ValidationError('Passwords must match')

        return v_password


    def clean_year(self):
        day = int(self.cleaned_data['day'])
        month = int(self.cleaned_data['month'])
        year = int(self.cleaned_data['year'])

        _, max_days = monthrange(year, month)


        if day > max_days:
            raise forms.ValidationError('Not valid Date')

        return year


class ProfileEditForm(forms.Form):
    username = forms.CharField(disabled=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(disabled=True, widget=forms.EmailInput(attrs={'class':'form-control'}))


    day = forms.IntegerField(
                            max_value=31,
                            min_value=1,
                            initial=date.today().day,
                            widget=forms.Select(
                                choices=[
                                    (day,day) for day in range(1, 31)
                                ],
                                attrs={'class':'form-select'}
                            )
                        )
    month = forms.IntegerField(
                            max_value=12,
                            min_value=1,
                            initial=MONTHS[date.today().month - 1],
                            widget=forms.Select(choices=MONTHS, attrs={'class': 'form-select'})
                        )
    year = forms.IntegerField(
                            min_value=1900,
                            max_value=date.today().year,
                            initial=date.today().year,
                            widget=forms.Select(
                                    choices=[
                                        (year, year) for year in range(1900, date.today().year + 1)
                                    ],
                                    attrs={'class':'form-select'}
                                )
                            )
    
    def clean_year(self):
        day = int(self.cleaned_data['day'])
        month = int(self.cleaned_data['month'])
        year = int(self.cleaned_data['year'])

        _, max_days = monthrange(year, month)

        if day > max_days:
            raise forms.ValidationError('Not Valid date')

        return year
        

    

src/users/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.db import transaction
from django.contrib.auth.models import User
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import send_mail
from django.conf import settings
from django.http import Http404

from users.models import UserExtension
from users.forms import UserRegistrationForm, ProfileEditForm
from users.tokens import password_token_gen

from datetime import date

from publications.models import Publication

class RegisterView(generic.View):
    template_name = 'user_registration.html'
    form_class = UserRegistrationForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, context={'form': form})


    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        error_message = None

        if form.is_valid():

            try:
                with transaction.atomic():
                    user = User()
                    extension = UserExtension()

                    user.username = form.cleaned_data['username']
                    user.first_name = form.cleaned_data['first_name']
                    user.last_name = form.cleaned_data['last_name']
                    user.email = form.cleaned_data['email']
                    user.set_password(form.cleaned_data['password'])

                    user.save()

                    day = int(form.cleaned_data['day'])
                    month = int(form.cleaned_data['month'])
                    year = int(form.cleaned_data['year'])

                    extension.birthdate = date(year, month, day)
                    extension.user = user

                    extension.save()

                    return redirect(reverse('users:login'))
            except:
                error_message = 'Something wen\'t wrong!'
        else:
            print(form.errors)

        return render(request, self.template_name, context={'form': form, 'error_message': error_message})


class ProfileView(generic.View):
    template_name = 'user_profile.html'

    def get_context_data(self) -> dict:
        context = {}

        publications = Publication.objects.filter(author=self.request.user).order_by('pub_date')
        context['publications'] = publications

        return context


    def get_initial(self) -> dict:
        initial = {}
        user = self.request.user
        extension = user.extension

        initial['username'] = user.username
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        initial['email'] = user.email

        initial['day'] = extension.birthdate.day
        initial['month'] =extension.birthdate.month
        initial['year'] = extension.birthdate.year
         
        return initial


    def get(self, request, *args, **kwargs):
        context = self.get_context_data()

        form = ProfileEditForm(initial=self.get_initial())
        context['form'] = form

        return render(request, self.template_name, context)
    

    def post(self, request, *args, **kwargs):
        form = ProfileEditForm(request.POST, initial=self.get_initial())
        context = self.get_context_data()

        user = request.user
        extension = user.extension

        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()

            day = int(form.cleaned_data['day'])
            month = int(form.cleaned_data['month'])
            year = int(form.cleaned_data['year'])

            extension.birthdate = date(year, month, day)
            extension.save()

            return redirect(reverse('users:profile'))
        else:
            print(form.errors)

        context['form'] = form

        return render(request, self.template_name, context)




class ProfileEditView(generic.FormView):
    template_name = 'user_profile_edit.html'
    form_class = ProfileEditForm

    def get_initial(self):
        initial = {}
        user = self.request.user
        extension = user.extension

        initial['username'] = user.username
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        initial['email'] = user.email

        initial['day'] = extension.birthdate.day
        initial['month'] =extension.birthdate.month
        initial['year'] = extension.birthdate.year
         

        return initial


    def form_valid(self, form: ProfileEditForm):
        
        user = self.request.user
        extension = user.extension

        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()

        day = int(form.cleaned_data['day'])
        month = int(form.cleaned_data['month'])
        year = int(form.cleaned_data['year'])


        extension.birthdate = date(year, month, day)
        extension.save()


        return redirect(reverse('users:profile'))



class LoginView(generic.View):
    template_name = 'login.html'
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


    def post(self, request, *args, **kwargs):
        username = self.request.POST.get('username')
        password = self.request.POST.get('password')
        error_message = ''

        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)
            return redirect(reverse('users:profile'))
        else:
            error_message = 'Username/Password aren\'t correct!'

        return render(request, self.template_name, {'error_message': error_message})


class LogoutView(generic.RedirectView):
    def get(self, request, *args, **kwargs):
        logout(request)

        return redirect(reverse('index'))


class PasswordResetView(generic.View):
    template_name = 'user_password_reset.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    

    def post(self, request, *args, **kwargs):
        error_message = ''
        sent_mail = False
        email = request.POST.get('email')

        try:
            email = str(email)
        except:
            error_message = 'Please enter a valid email!'

        if len(error_message) == 0:
            user = User.objects.filter(email=email).first()
            sent_mail = True
            if user:
                token = password_token_gen.make_token(user)
                encodeduid = urlsafe_base64_encode(force_bytes(user.pk))

                url = settings.SITE_URL + reverse('users:restablish_password') + f'?token={token}&uuid={encodeduid}'
                send_mail(
                    'Reset Password',
                    f'Follow this url to reset password \nURL: {url}',
                    from_email='flasker@flasker.com',
                    recipient_list=['test@test.com']
                )

        return render(request, self.template_name, {'error_message': error_message, 'sent_mail': sent_mail})


class RestablishPasswordView(generic.View):
    template_name = 'user_restablish_password.html'


    def get(self, request, *args, **kwargs):

        encoded_uuid = request.GET.get('uuid')
        token = request.GET.get('token')

        if not encoded_uuid or not token:
            raise Http404
        
        try:
            uuid = force_str(urlsafe_base64_decode(encoded_uuid))
            user = User.objects.filter(pk=uuid).first()
        except ValueError:
            raise Http404


        if not password_token_gen.check_token(user, token):
            raise Http404
        
        return render(request, self.template_name)


    def post(self, request, *args, **kwargs):

        encoded_uuid = request.GET.get('uuid')
        token = request.GET.get('token')
        error_message = ''


        if not encoded_uuid or not token:
            raise Http404
        
        try:
            uuid = force_str(urlsafe_base64_decode(encoded_uuid))
            user = User.objects.filter(pk=uuid).first()
        except:
            raise Http404

        if not password_token_gen.check_token(user, token):
            raise Http404
        
        unsanitized_password = request.POST.get('password')
        unsanitized_v_password = request.POST.get('v_password')

        password = str(unsanitized_password)
        v_password = str(unsanitized_v_password)

        if password == v_password:
            user.set_password(password)
            user.save()
            return redirect(reverse('users:login'))
        else:
            error_message = 'Passwords don\'t match'

        return render(request, self.template_name, {'error_message': error_message })

src/users/templates/login.html
{% extends 'base.html' %}


{% block body %}
    <div>
        <form method="post" class="bg-dark p-3 rounded text-white" style="margin-left: 30%; margin-right: 30%;">
            <h3>Log In</h3>
            <hr>
            {% csrf_token %}
            
            {{ error_message }}
            
            <label for="usernameInput" class="form-label">Username:</label>
            <div>
                <input type="text" class="form-control" name="username" id="usernameInput" required>
            </div>
            
            <label for="passwordInput" class="form-label">Password:</label>
            <div>
                <input type="password" class="form-control" name="password" id="passwordInput" required>
            </div>
            <small><a href="{% url 'users:reset_password' %}" class="fw-semibold">Reset Password</a></small>
            <div class="d-flex mt-3">
                <a href="{% url 'index' %}" class="ms-auto btn btn-outline-warning">Cancel</a>
                <input type="submit" value="Log In" class="btn btn-light ms-1">
            </div>
        </form>
    </div>    
        
{% endblock %}

src/users/templates/user_password_reset.html
{% extends 'base.html' %}

{% block body %}


    <form method="post" class="bg-dark p-3 rounded text-white" style="margin-left: 30%; margin-right: 30%;">
        <h1>Reset Password</h1>
        <hr>
        {% if sent_mail %}
            <div class="alert alert-dark alert-dismissible fade show text-center" role="alert">
                Email has been Sent!
                <button type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="close"></button>
            </div>   
        {% endif %}
        {{ error_message }} 
        {% csrf_token %}
        <label for="" class="form-label">Email</label>
        <div>
            <input type="email" name="email" id="email" class="form-control" required>
        </div>

        <div class="d-flex mt-3">
            <a href="{% url 'users:login' %}" class="ms-auto btn btn-outline-warning">Cancel</a>
            <input type="submit" value="Reset" class="ms-1 btn btn-light">
        </div>
    </form>

{% endblock %}

src/users/templates/user_profile.html
{% extends 'base.html' %}

{% block body %}

    <div class="row">
        <div class="col-md-4">
            <div class="bg-light rounded p-3">
                <div id="profile-info">
                    <h4>{{ user.username }}</h4>
                    <hr>
                    <strong>Name:</strong> {{ user }}<br>
                    <strong>Email:</strong> {{ user.email }} <br>
                    <strong>Birthdate:</strong> {{ user.extension.birthdate }} <br>
                    <div class="d-flex justify-content-center">
                        <a href="" id="edit-button" class="mt-3" style="text-decoration: none;">
                            Edit  <i class="fa-solid fa-pencil"></i>
                        </a>
                    </div>
                    <!-- <button id="edit-button">Edit</button> -->
                </div>
                
                <form method="post" id="edit-form" style="display: none;">
                    {% csrf_token %}
                    {{ form.non_field_errors }}

                    <label for="" class="form-label">{{ form.username.label }}</label>
                    <div>
                        {{ form.username.errors }}
                        {{ form.username }}
                    </div>
                    
                    <label for="" class="form-label">{{ form.first_name.label }}</label>
                    <div>
                        {{ form.first_name.errors }}
                        {{ form.first_name }}
                    </div>
                    
                    <label for="" class="form-label">{{ form.last_name.label }}</label>
                    <div>
                        {{ form.last_name.errors }}
                        {{ form.last_name }}
                    </div>
                    
                    <label for="" class="form-label">{{ form.email.label }}</label>
                    <div>
                        {{ form.email.errors }}
                        {{ form.email }}
                    </div>

                    <label for="" class="form-label">Birthdate</label>
                    <div class="mb-2">
                        {{ form.day.errors }}
                        {{ form.month.errors }}
                        {{ form.year.errors }}
                        <div class="row">
                            <div class="col-sm-4">
                                {{ form.day }}
                            </div>
                            <div class="col-sm-4">
                                {{ form.month }}
                            </div>
                            <div class="col-sm-4">
                                {{ form.year }}
                            </div>
                        </div>
                    </div>
                    
                    <div class="d-flex mt-3">
                        <button type="button" class="btn btn-outline-warning ms-auto" id="cancel-form">Cancelar</button>
                        <input type="submit" value="Save" class="btn btn-primary ms-1">
                    </div>
                </form>

            </div>
        </div>

        <div class="col-md-8">
            {% for pub in publications %}
            <div class="bg-light p-2 rounded d-flex align-items-center mb-3">
                <div>
                    <a href="{% url 'publications:publication_detail' pk=pub.pk %}">{{ pub.title }}</a> <br>
                    <small> <strong>By:</strong> {{ pub.author.username }}</small>
                </div>
                    <small class="ms-auto">{{ pub.pub_date }}</small>
            </div>
        
            {% empty %}
                <div class="d-flex justify-content-center">
                    <div>

                        <h4 class="text-center">No Publications Yet!</h4>
                        <a href="{% url 'publications:publication_create' %}" class="text-center" style="text-decoration: none;">
                            Add One <i class="fa-sharp fa-solid fa-plus"></i>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
        
        
    </div>

    <script>
        let editForm = document.getElementById('edit-form');
        let profileInfo = document.getElementById('profile-info');
        let cancelFormBtn = document.getElementById('cancel-form');
        let editProfileBtn = document.getElementById('edit-button');

        editProfileBtn.addEventListener('click',(event)=>{
            event.preventDefault();
            editForm.style.display = 'block';
            profileInfo.style.display = 'none';
        });

        cancelFormBtn.addEventListener('click', event=>{
            editForm.style.display = 'none';
            profileInfo.style.display = 'block';
        });


    </script>

{% endblock %}

src/users/templates/user_profile_edit.html
{% extends 'base.html' %}

{% block body %}

    <h4>{{ user.username }}</h4>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'users:profile' %}">Cancel</a>
        <input type="submit" value="Save">
    </form>

{% endblock  %}

src/users/templates/user_registration.html
{% extends 'base.html' %}

{% block body %}

    <div>
        <form method="post" class="bg-dark p-3 rounded text-white" style="margin-left: 30%; margin-right: 30%;">
            <h3>Register</h3>
            <hr>
            {% csrf_token %}
            {{ form.non_field_errors }}

            <label for="" class="form-label">{{ form.username.label }}</label>
            <div class="mb-2">
                {{ form.username.errors }}
                {{ form.username }}
            </div>

            <div class="row mb-2">
                <div class="col-sm-6">
                    <label for="" class="form-label">{{ form.first_name.label }}</label>
                    <div>
                        {{ form.first_name.errors }}
                        {{ form.first_name }}
                    </div>
                </div>

                <div class="col-sm-6">
                    <label for="" class="form-label">{{ form.last_name.label }}</label>
                    <div>
                        
                        {{ form.last_name.errors }}
                        {{ form.last_name }}
                    </div>
                </div>
            </div>

            <label for="" class="form-label">{{ form.email.label }}</label>
            <div class="mb-2">
                {{ form.email.errors }}
                {{ form.email }}
            </div>

            <label for="" class="form-label">Birthdate</label>
            <div class="mb-2">
                {{ form.day.errors }}
                {{ form.month.errors }}
                {{ form.year.errors }}
                <div class="row">
                    <div class="col-sm-4">
                        {{ form.day }}
                    </div>
                    <div class="col-sm-4">
                        {{ form.month }}
                    </div>
                    <div class="col-sm-4">
                        {{ form.year }}
                    </div>
                </div>
            </div>

            <div class="mb-2">
                <div class="row">
                    <div class="col-sm-6">
                        <label for="" class="form-label">{{ form.password.label }}</label>
                        <div>
                            {{ form.password.errors }}
                            {{ form.password }}
                        </div>
                    </div>
                    
                    <div class="col-sm-6">
                        <label for="" class="form-label">{{ form.verify_password.label }}</label>
                        <div>
                            {{ form.verify_password.errors }}
                            {{ form.verify_password }}
                        </div>
                    </div>
                </div>
            </div>

            <div class="d-flex mt-3">
                <a href="{% url 'index' %}" class="ms-auto btn btn-outline-warning">Cancel</a>
                <input type="submit" value="Register" class="ms-1 btn btn-light">
            </div>
        </form>
    </div>

{% endblock %}

src/users/templates/user_restablish_password.html
{% extends 'base.html' %}

{% block body %}

    <form method="post" class="bg-dark p-3 shadow rounded text-white" style="margin-left: 30%; margin-right: 30%;">
        {% csrf_token %}
        {{ error_message }}
        <label for="" class="form-label">Password</label>
        <div>
            <input type="password" name="password" id="password" class="form-control" required>
        </div>

        <label for="" class="form-label">Verify Password</label>
        <div>
            <input type="password" name="v_password" id="v_password" class="form-control" required>
        </div>

        <div class="d-flex mt-3">
            <a href="{% url 'index' %}" class="ms-auto btn btn-outline-warning">Cancel</a>
            <input type="submit" class="ms-1 btn btn-light" value="Reset">
        </div>
    </form>
{% endblock %}